services:
  mongo:
    image: mongo:latest
    container_name: mongo
    networks:
      - bloodnet

  app:
    build: .
    container_name: app
    ports:
      - "8085:8085"
    depends_on:
      - mongo
    networks:
      - bloodnet

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3001:80"
    depends_on:
      - app
    networks:
      - bloodnet

networks:
  bloodnet:
    driver: bridge
